services:
  display-manager:
    image: display-manager:latest
    ports:
      - "8080:8080"
    volumes:
      - /home/jkumar/github/display-manager/data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /home/jkumar/.Xauthority:/tmp/.Xauthority:ro
    environment:
      DB_PATH: /data/display.db
      DISPLAY: ":0"
      XAUTHORITY: /tmp/.Xauthority
    restart: always
    deploy:
      resources:
        limits:
          memory: 256m
